version: '3.7'

services:
  seaside-rtmp-standalone:
    build:
      context: ./rtmp-standalone
    ports:
      # RTMP
      - 1935:1935
      # HLS/Dash
      - 8080:8080
  seaside-rtmp-auth:
    build:
      context: ./rtmp-auth
    command: [ "./rtmp-auth", "-apiAddr", "0.0.0.0:8081", "-frontendAddr", "0.0.0.0:8082" ]
    ports:
      - 8081:8080
      - 8082:8082
    volumes:
      - ./rtmp-auth/config.toml:/app/config.toml
      - ./volumes/rtmp-auth:/app/storage
  