version: '3.7'

services:
  seaside-rtmp-auth:
    build:
      context: ./rtmp-auth
    command: [ "./rtmp-auth", "-apiAddr", "0.0.0.0:8080", "-frontendAddr", "0.0.0.0:8082" ]
    ports:
      - 8080:8080
      - 8082:8082
    volumes:
      - ./rtmp-auth/config.toml:/app/config.toml
      - ./volumes/rtmp-auth:/app/storage
  seaside-rtmp:
    image: tiangolo/nginx-rtmp
    links:
      - seaside-rtmp-auth
    ports:
      # RTMP
      - 1935:1935
      # HLS/Dash
      - 8088:8088
    volumes:
      - ./nginx-confs/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-confs/conf.d:/etc/nginx/conf.d/
      - ./nginx-confs/rtmp-sites:/etc/nginx/rtmp-sites/
      # Dash/HLS splits
      - ./volumes/nginx-web:/var/www/html/stream
  