[http]
# List of RTMP apps
applications = ["live"]

# Path prefix to allow frontend to run on a subpath
#prefix = ""

# Allow CSRF cookie to be sent across http-connection, not recommended for production
#insecure = false

[store]
# Set store backend (file|consul)
# backend = "file"

[store.file]
# Configure file storage path relative to working directory
path = "./storage/store.db"
